### ISSUE TITLE
Internal error got on Julia1.2.0

### ISSUE THREAD

**Issue by terasakisatoshi** [JuliaMath/HCubature.jl#21]
One of the code using HCubature.jl got internal error on Julia1.2.0 .
Here is an example how to reproduce the error:

```
$ docker run --rm -it julia:1.2.0 \
julia -e 'using Pkg; Pkg.add("HCubature")
          using HCubature
          f(x, y) = x*y^2
          g(f; m=1) = hcubature(w->f(w[1], w[2]), [0,0], [1,1])
          @show g(f)'
```

Result: [see my gist](https://gist.github.com/terasakisatoshi/682bd28e09d004a50f76fb69349b9187)

On the other hand, It works for Julia 1.1.1, 1.3.0 or 1.4.0-DEV(Commit d3250fe)

```
docker run --rm -it julia:1.3.0 \
julia -e 'using Pkg; Pkg.add("HCubature")
          using HCubature
          f(x, y) = x*y^2
          g(f; m=1) = hcubature(w->f(w[1], w[2]), [0,0], [1,1])
          @show g(f)'
```

**Comment by mikeingold** [comment]
Support for Julia versions below `v1.6` was removed earlier this year in commit #0e8470d:

https://github.com/JuliaMath/HCubature.jl/blob/0e8470d64aa00b1a015228f08449f7124f1d6b07/Project.toml#L13

Since this Issue was specific to Julia `v1.2.0` and apparently isn’t reproduced on newer versions, it’s probably safe to close.
