### ISSUE TITLE
Errors with BigFloat boundaries

### ISSUE THREAD

**Issue by araujoms** [JuliaMath/HCubature.jl#60]
The following function errors when I call it as `erf(BigFloat)`. It should work, no? It doesn't complain if I call it with other funny types that are nevertheless `isbits`.

```julia
function erf(T)
    lb, ub = T(0), T(1)
    f(x) = exp(-x^2)
    sol = hquadrature(f, lb, ub)
    return sol[1] 
end
```

**Comment by stevengj** [comment]
If you want to do 1d `BigFloat` quadrature, I would highly recommend using QuadGK instead, since QuadGK lets you increase the quadrature order (it is a good idea to increase the order roughly in proportion to the precision).

That being said, I agree that this should work (even if it is suboptimal).  Maybe we can make use of https://github.com/JuliaArrays/StaticArrays.jl/issues/799

**Comment by araujoms** [comment]
The actual integral I need to solve is 2d, I only simplified it for the MWE.

Do you mean for example, in line 67 of HCubature.jl, declare `ma = similar(a)` instead of `ma = MVector(a)`?

**Comment by stevengj** [comment]
Sorry, not `similar` because we need to copy the contents.  Rather, `Base.copymutable(a)`.

**Comment by stevengj** [comment]
The annoyance here is that `Base.copymutable(a)`, which calls `similar` and then `copyto!`, may be less efficient than `MVector(a)` for the cases where `MVector` *does* work.  

It seems like StaticArrays.jl should ideally implement a specialized `Base.copymutable` method?

**Comment by araujoms** [comment]
`StaticArrays` is above my pay grade.

But if this is the only place then I'm sure there will be no difference in performance. Looking around a bit, line 15 of `genz-malik.jl` will also certainly cause trouble. But there `similar` is enough, no copying is needed.

I can give it a try tomorrow; to see if I can fix it and benchmark it. Can you suggest a test case for benchmarking?
